### ISSUE TITLE
no output file

### ISSUE THREAD

**Issue by thethor12** [Insight-deviler/D8-Dex#1]
There is no output file after I select a jar file ......i tried on many api versions..... using Android [12.1..

**Comment by sohaillxd** [comment]
Can anyone convert this to dex for me?

**Comment by S-Sarath10** [comment]
1. Please check whether your Jar2Dex folder has all the files such as android.jar, d8.jar, rt.jar.
2. If you have all these files and the app isn't converting jar to dex then change the Min API to above 21.
3. Even though this app is said to convert Jar to Dex it can't convert all types of jar files especially the one's whose size is large.
4. Tell or send me  what type of jar file you have trying to convert. So that I can check it.
